# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 05:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_borderkeeper', '__first__'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricetype',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_framework_borderkeeper.Client'),
        ),
        migrations.AddField(
            model_name='productinstance',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_framework_borderkeeper.Client'),
        ),
        migrations.AddField(
            model_name='productinstance',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rest_framework_borderkeeper.Owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productstatus',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_framework_borderkeeper.Client'),
        ),
    ]
