# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20161020_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Provision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(auto_now_add=True)),
                ('end_at', models.DateTimeField()),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Local')),
                ('product_instances', models.ManyToManyField(to='products.ProductInstance')),
            ],
        ),
        migrations.RenameField(
            model_name='productdata',
            old_name='share',
            new_name='shelf_share',
        ),
        migrations.AddField(
            model_name='productdata',
            name='shelf_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productdata',
            name='provision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Provision'),
        ),
        migrations.AddField(
            model_name='productdata',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductStatus'),
        ),
    ]
