# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinstance',
            name='code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
