# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productinstance_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresenceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Local')),
                ('product_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductInstance')),
                ('provision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Provision')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductStatus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PriceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Local')),
                ('product_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductInstance')),
                ('provision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Provision')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShareData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shelf_share', models.IntegerField(blank=True, null=True)),
                ('shelf_stock', models.IntegerField(blank=True, null=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Local')),
                ('product_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductInstance')),
                ('provision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Provision')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
