# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_presencedata_pricedata_sharedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presencedata',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.ProductStatus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricedata',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sharedata',
            name='shelf_share',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sharedata',
            name='shelf_stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
