# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20161123_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productinstance',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
