# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20161128_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinstance',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Category'),
        ),
        migrations.AlterField(
            model_name='productinstance',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Client'),
        ),
    ]
