# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20161130_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='local_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='place_id',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
