# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_borderkeeper', '0002_instance_client'),
        ('products', '0017_auto_20161130_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinstance',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rest_framework_borderkeeper.Owner'),
            preserve_default=False,
        ),
    ]
