# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20161206_1921'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
