# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_borderkeeper', '0002_instance_client'),
        ('products', '0020_delete_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricetype',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_framework_borderkeeper.Client'),
        ),
        migrations.AddField(
            model_name='productinstance',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_framework_borderkeeper.Client'),
        ),
        migrations.AddField(
            model_name='productstatus',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_framework_borderkeeper.Client'),
        ),
    ]
